{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composemediaplayer/dev/composemediaplayer-dev.module",
    "group": "io.github.kdroidfilter",
    "module": "composemediaplayer",
    "version": "dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.vinceglb",
          "module": "filekit-core",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "mediaplayer-wasm-js.klib",
          "url": "composemediaplayer-wasm-js-dev.klib",
          "size": 199678,
          "sha512": "349524eda4ef1d39461c7451b80fba58f0008ab9b83b537d4d0670179298597b2ac9c098f73fe25998bdc3cb63ba55205a75d4a2c6aaedc83889b7121d49c819",
          "sha256": "c0961bb034f6b3c92193bb723eb40b4c3489f442f27cc684b9d504a4448fa9d2",
          "sha1": "5714651db8cf0bcfb5cbbdabe9a1ff58e6598362",
          "md5": "366ee5eb28a30f5620d42a8cbb6562ec"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.vinceglb",
          "module": "filekit-core",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "mediaplayer-wasm-js.klib",
          "url": "composemediaplayer-wasm-js-dev.klib",
          "size": 199678,
          "sha512": "349524eda4ef1d39461c7451b80fba58f0008ab9b83b537d4d0670179298597b2ac9c098f73fe25998bdc3cb63ba55205a75d4a2c6aaedc83889b7121d49c819",
          "sha256": "c0961bb034f6b3c92193bb723eb40b4c3489f442f27cc684b9d504a4448fa9d2",
          "sha1": "5714651db8cf0bcfb5cbbdabe9a1ff58e6598362",
          "md5": "366ee5eb28a30f5620d42a8cbb6562ec"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "mediaplayer-wasm-js-sources.jar",
          "url": "composemediaplayer-wasm-js-dev-sources.jar",
          "size": 38847,
          "sha512": "a5f29a0c9ab8b885c00e123c116657a1d48c63e58a5179cd58c637b7ff252e6ba3add0d599d93481684db5b3c95bc1002ee0b45140eb11e981bf31320e996787",
          "sha256": "f52f2c764d4b28f606f4c9ced9510fd5a09d47d9d22e954fc68d1fb13b6fceb3",
          "sha1": "8e6b92419e30d1ba7eb56f8e8c204c32b67e21ac",
          "md5": "cfe0f108a8bcfedf8fcccc3012520dd6"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "io.github.vinceglb",
          "module": "filekit-core",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "mediaplayer.kotlin_resources.zip",
          "url": "composemediaplayer-wasm-js-dev-kotlin_resources.kotlin_resources.zip",
          "size": 394,
          "sha512": "f9068dbefe9c11e3051287e15c2cf34fb0854208f68c3b8561e7d5c13b6eede991324f0a2e8d00b862e7175b360216c92dcbb529ca915522be360edd2e6b42cd",
          "sha256": "a38ba5bdc469950e4eed738b7eaed378291571a00d39f78dd8b7c78488aa5014",
          "sha1": "13e5b7499336de3bd210ddb32e141252883e1f65",
          "md5": "aeaf7a8c0316a48b8c3e8abf542ff880"
        }
      ]
    }
  ]
}
