{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composemediaplayer/dev/composemediaplayer-dev.module",
    "group": "io.github.kdroidfilter",
    "module": "composemediaplayer",
    "version": "dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.vinceglb",
          "module": "filekit-core",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "mediaplayer-jvm.jar",
          "url": "composemediaplayer-jvm-dev.jar",
          "size": 590900,
          "sha512": "1aff0c0c228af7e516fe56ef95c01fde9cf3421ba4a57fba9b626e4a07b882cf4a8cff08ee21d857eac6f565efe7fa0c24c52b683cc8cb2bf97f822bb3877a55",
          "sha256": "1fbcfff6339335bf6526faa0edf52c412b230971d4e6cafeec7a588adba4bb82",
          "sha1": "bcbffcecdf8c3e810e1a1067a2824782d35c6ed1",
          "md5": "5092439f528fbf0dd242cf06144c0ef2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.vinceglb",
          "module": "filekit-core",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "mediaplayer-jvm.jar",
          "url": "composemediaplayer-jvm-dev.jar",
          "size": 590900,
          "sha512": "1aff0c0c228af7e516fe56ef95c01fde9cf3421ba4a57fba9b626e4a07b882cf4a8cff08ee21d857eac6f565efe7fa0c24c52b683cc8cb2bf97f822bb3877a55",
          "sha256": "1fbcfff6339335bf6526faa0edf52c412b230971d4e6cafeec7a588adba4bb82",
          "sha1": "bcbffcecdf8c3e810e1a1067a2824782d35c6ed1",
          "md5": "5092439f528fbf0dd242cf06144c0ef2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mediaplayer-jvm-sources.jar",
          "url": "composemediaplayer-jvm-dev-sources.jar",
          "size": 74371,
          "sha512": "2bdaeb96b457beba13e52d463db2f2c83e275052f67028cce80029afc8bc5dc3e369f870a44a802fb760e3de7879959df79b157abcd78e03359542b0bb71d11b",
          "sha256": "20da9d265349c87a4e378852537fe6cf8177905230c0cb1569123df3a3d3bb21",
          "sha1": "2114c25cbcfc764321921a9b6c0f7831bfa3ea9d",
          "md5": "0bded0b78aef21f77b05726178360bd9"
        }
      ]
    }
  ]
}
